import type { ScavioClientOptions } from './client.js';
import { createScavioExtractTool } from './extract.js';
import {
  createScavioWalmartCategoryTool,
  createScavioWalmartOffersTool,
  createScavioWalmartProductTool,
  createScavioWalmartReviewsTool,
  createScavioWalmartSearchTool,
  createScavioWalmartSellerProductsTool,
  createScavioWalmartSellerTool,
} from './walmart.js';
import {
  createScavioThreadsPostCommentsTool,
  createScavioThreadsPostTool,
  createScavioThreadsProfileTool,
  createScavioThreadsSearchUsersTool,
  createScavioThreadsUserPostsTool,
  createScavioThreadsUserRepliesTool,
} from './threads.js';
import {
  createScavioKuaishouCommentRepliesTool,
  createScavioKuaishouProfileTool,
  createScavioKuaishouSearchLiveTool,
  createScavioKuaishouSearchTool,
  createScavioKuaishouSearchUsersTool,
  createScavioKuaishouSearchVideosTool,
  createScavioKuaishouTagFeedTool,
  createScavioKuaishouTrendingTool,
  createScavioKuaishouUserLiveTool,
  createScavioKuaishouUserPostsTool,
  createScavioKuaishouUserResolveTool,
  createScavioKuaishouVideoCommentsTool,
  createScavioKuaishouVideoTool,
  createScavioKuaishouVideosBatchTool,
} from './kuaishou.js';
import {
  createScavioEbayProductTool,
  createScavioEbaySearchTool,
  createScavioEbaySellerTool,
} from './ebay.js';
import {
  createScavioTargetCategoryTool,
  createScavioTargetProductTool,
  createScavioTargetReviewsTool,
  createScavioTargetSearchTool,
} from './target.js';
import {
  createScavioHomeDepotProductTool,
  createScavioHomeDepotReviewsTool,
  createScavioHomeDepotSearchTool,
} from './home-depot.js';
import {
  createScavioZillowAgentReviewsTool,
  createScavioZillowPropertyTool,
  createScavioZillowSearchTool,
} from './zillow.js';
import {
  createScavioBookingHotelTool,
  createScavioBookingReviewsTool,
  createScavioBookingSearchTool,
} from './booking.js';
import {
  createScavioTripadvisorLocationTool,
  createScavioTripadvisorLocationsTool,
  createScavioTripadvisorReviewsTool,
  createScavioTripadvisorSearchTool,
} from './tripadvisor.js';
import {
  createScavioIndeedCompanyReviewsTool,
  createScavioIndeedCompanyTool,
  createScavioIndeedJobTool,
  createScavioIndeedSearchTool,
} from './indeed.js';
import {
  createScavioAirbnbListingTool,
  createScavioAirbnbReviewsTool,
  createScavioAirbnbSearchTool,
} from './airbnb.js';
import {
  createScavioGlassdoorCompaniesTool,
  createScavioGlassdoorCompanyTool,
  createScavioGlassdoorReviewsTool,
  createScavioGlassdoorSalariesTool,
} from './glassdoor.js';
import {
  createScavioYelpBusinessTool,
  createScavioYelpReviewsTool,
  createScavioYelpSearchTool,
} from './yelp.js';
import {
  createScavioAppStoreAppTool,
  createScavioAppStoreReviewsTool,
  createScavioAppStoreSearchTool,
} from './app-store.js';
import {
  createScavioGooglePlayAppTool,
  createScavioGooglePlayReviewsTool,
  createScavioGooglePlaySearchTool,
} from './google-play.js';
import {
  createScavioSecCompanyTool,
  createScavioSecConceptTool,
  createScavioSecFactsTool,
  createScavioSecFilingsTool,
  createScavioSecLookupTool,
  createScavioSecSearchTool,
} from './sec.js';
import {
  createScavioRedfinMarketTool,
  createScavioRedfinPropertyTool,
  createScavioRedfinSearchTool,
} from './redfin.js';
import {
  createScavioCompaniesHouseCompanyTool,
  createScavioCompaniesHouseFilingHistoryTool,
  createScavioCompaniesHouseOfficersTool,
  createScavioCompaniesHouseSearchTool,
} from './companies-house.js';
import {
  createScavioG2ProductTool,
  createScavioG2ReviewsTool,
  createScavioG2SearchTool,
} from './g2.js';
import {
  createScavioCapterraProductTool,
  createScavioCapterraReviewsTool,
  createScavioCapterraSearchTool,
} from './capterra.js';
import {
  createScavioGoogleAdsAdvertisersTool,
  createScavioGoogleAdsCreativeTool,
  createScavioGoogleAdsSearchTool,
} from './google-ads.js';
import {
  createScavioMetaAdsAdTool,
  createScavioMetaAdsAdvertiserTool,
  createScavioMetaAdsSearchTool,
} from './meta-ads.js';
import {
  createScavioAmazonOffersTool,
  createScavioAmazonProductTool,
  createScavioAmazonSearchTool,
} from './amazon.js';
import {
  createScavioGoogleAiModeTool,
  createScavioGoogleFlightsTool,
  createScavioGoogleHotelsDetailTool,
  createScavioGoogleHotelsTool,
  createScavioGoogleMapsPlaceTool,
  createScavioGoogleMapsReviewsTool,
  createScavioGoogleMapsSearchTool,
  createScavioGoogleNewsTool,
  createScavioGoogleSearchTool,
  createScavioGoogleShoppingProductTool,
  createScavioGoogleShoppingStoresTool,
  createScavioGoogleShoppingTool,
  createScavioGoogleTrendingTool,
  createScavioGoogleTrendsTool,
} from './google.js';
import {
  createScavioInstagramCommentRepliesTool,
  createScavioInstagramPostCommentsTool,
  createScavioInstagramPostTool,
  createScavioInstagramProfileTool,
  createScavioInstagramSearchHashtagsTool,
  createScavioInstagramSearchUsersTool,
  createScavioInstagramUserFollowersTool,
  createScavioInstagramUserFollowingsTool,
  createScavioInstagramUserPostsTool,
  createScavioInstagramUserReelsTool,
  createScavioInstagramUserStoriesTool,
  createScavioInstagramUserTaggedTool,
} from './instagram.js';
import {
  createScavioLinkedinCompanyPostsTool,
  createScavioLinkedinCompanyTool,
  createScavioLinkedinJobTool,
  createScavioLinkedinPersonAboutTool,
  createScavioLinkedinPersonPostsTool,
  createScavioLinkedinPersonTool,
  createScavioLinkedinPostCommentsTool,
  createScavioLinkedinPostTool,
  createScavioLinkedinSearchJobsTool,
} from './linkedin.js';
import {
  createScavioRedditCommentRepliesTool,
  createScavioRedditPopularTool,
  createScavioRedditPostCommentsTool,
  createScavioRedditPostTool,
  createScavioRedditSearchSuggestionsTool,
  createScavioRedditSearchTool,
  createScavioRedditSubredditPostsTool,
  createScavioRedditSubredditTool,
  createScavioRedditTrendingTool,
  createScavioRedditUserCommentsTool,
  createScavioRedditUserPostsTool,
  createScavioRedditUserTool,
} from './reddit.js';
import {
  createScavioTiktokShopCategoriesTool,
  createScavioTiktokShopCategoryProductsTool,
  createScavioTiktokShopProductReviewsTool,
  createScavioTiktokShopProductTool,
  createScavioTiktokShopResolveTool,
  createScavioTiktokShopSearchSuggestionsTool,
  createScavioTiktokShopSearchTool,
  createScavioTiktokShopShopProductsTool,
} from './tiktok-shop.js';
import {
  createScavioTiktokCommentRepliesTool,
  createScavioTiktokHashtagTool,
  createScavioTiktokHashtagVideosTool,
  createScavioTiktokProfileTool,
  createScavioTiktokSearchUsersTool,
  createScavioTiktokSearchVideosTool,
  createScavioTiktokUserFollowersTool,
  createScavioTiktokUserFollowingsTool,
  createScavioTiktokUserPostsTool,
  createScavioTiktokVideoCommentsTool,
  createScavioTiktokVideoTool,
} from './tiktok.js';
import {
  createScavioXSearchTool,
  createScavioXTrendingTool,
  createScavioXTweetCommentsTool,
  createScavioXTweetRetweetersTool,
  createScavioXTweetTool,
  createScavioXUserFollowersTool,
  createScavioXUserFollowingsTool,
  createScavioXUserMediaTool,
  createScavioXUserRepliesTool,
  createScavioXUserTool,
  createScavioXUserTweetsTool,
} from './x.js';
import {
  createScavioYoutubeChannelCommunityTool,
  createScavioYoutubeChannelResolveTool,
  createScavioYoutubeChannelSearchTool,
  createScavioYoutubeChannelShortsTool,
  createScavioYoutubeChannelTool,
  createScavioYoutubeChannelVideosTool,
  createScavioYoutubeCommentRepliesTool,
  createScavioYoutubeCommentsTool,
  createScavioYoutubeRelatedTool,
  createScavioYoutubeSearchTool,
  createScavioYoutubeShortsTool,
  createScavioYoutubeStreamsTool,
  createScavioYoutubeSuggestionsTool,
  createScavioYoutubeTranscriptTool,
  createScavioYoutubeVideoTool,
} from './youtube.js';

/**
 * Every Scavio tool, keyed by name. This list and the exact-order assertion in
 * src/__tests__/tools.test.ts are the package's two hardcoded registries - a new
 * tool must land in both, or it ships unreachable.
 */
export function createScavioTools(config?: ScavioClientOptions) {
  return {
    scavioExtract: createScavioExtractTool(config),
    scavioGoogleSearch: createScavioGoogleSearchTool(config),
    scavioGoogleAiMode: createScavioGoogleAiModeTool(config),
    scavioGoogleMapsSearch: createScavioGoogleMapsSearchTool(config),
    scavioGoogleMapsPlace: createScavioGoogleMapsPlaceTool(config),
    scavioGoogleMapsReviews: createScavioGoogleMapsReviewsTool(config),
    scavioGoogleShopping: createScavioGoogleShoppingTool(config),
    scavioGoogleShoppingProduct: createScavioGoogleShoppingProductTool(config),
    scavioGoogleShoppingStores: createScavioGoogleShoppingStoresTool(config),
    scavioGoogleFlights: createScavioGoogleFlightsTool(config),
    scavioGoogleHotels: createScavioGoogleHotelsTool(config),
    scavioGoogleHotelsDetail: createScavioGoogleHotelsDetailTool(config),
    scavioGoogleNews: createScavioGoogleNewsTool(config),
    scavioGoogleTrends: createScavioGoogleTrendsTool(config),
    scavioGoogleTrending: createScavioGoogleTrendingTool(config),
    scavioAmazonSearch: createScavioAmazonSearchTool(config),
    scavioAmazonProduct: createScavioAmazonProductTool(config),
    scavioAmazonOffers: createScavioAmazonOffersTool(config),
    scavioWalmartSearch: createScavioWalmartSearchTool(config),
    scavioWalmartProduct: createScavioWalmartProductTool(config),
    scavioWalmartReviews: createScavioWalmartReviewsTool(config),
    scavioWalmartCategory: createScavioWalmartCategoryTool(config),
    scavioWalmartOffers: createScavioWalmartOffersTool(config),
    scavioWalmartSeller: createScavioWalmartSellerTool(config),
    scavioWalmartSellerProducts: createScavioWalmartSellerProductsTool(config),
    scavioYoutubeSearch: createScavioYoutubeSearchTool(config),
    scavioYoutubeShorts: createScavioYoutubeShortsTool(config),
    scavioYoutubeSuggestions: createScavioYoutubeSuggestionsTool(config),
    scavioYoutubeVideo: createScavioYoutubeVideoTool(config),
    scavioYoutubeComments: createScavioYoutubeCommentsTool(config),
    scavioYoutubeCommentReplies: createScavioYoutubeCommentRepliesTool(config),
    scavioYoutubeTranscript: createScavioYoutubeTranscriptTool(config),
    scavioYoutubeRelated: createScavioYoutubeRelatedTool(config),
    scavioYoutubeChannelSearch: createScavioYoutubeChannelSearchTool(config),
    scavioYoutubeChannel: createScavioYoutubeChannelTool(config),
    scavioYoutubeChannelVideos: createScavioYoutubeChannelVideosTool(config),
    scavioYoutubeChannelShorts: createScavioYoutubeChannelShortsTool(config),
    scavioYoutubeChannelCommunity: createScavioYoutubeChannelCommunityTool(config),
    scavioYoutubeChannelResolve: createScavioYoutubeChannelResolveTool(config),
    scavioYoutubeStreams: createScavioYoutubeStreamsTool(config),
    scavioRedditSearch: createScavioRedditSearchTool(config),
    scavioRedditSearchSuggestions: createScavioRedditSearchSuggestionsTool(config),
    scavioRedditPost: createScavioRedditPostTool(config),
    scavioRedditPostComments: createScavioRedditPostCommentsTool(config),
    scavioRedditCommentReplies: createScavioRedditCommentRepliesTool(config),
    scavioRedditSubreddit: createScavioRedditSubredditTool(config),
    scavioRedditSubredditPosts: createScavioRedditSubredditPostsTool(config),
    scavioRedditUser: createScavioRedditUserTool(config),
    scavioRedditUserPosts: createScavioRedditUserPostsTool(config),
    scavioRedditUserComments: createScavioRedditUserCommentsTool(config),
    scavioRedditPopular: createScavioRedditPopularTool(config),
    scavioRedditTrending: createScavioRedditTrendingTool(config),
    scavioTiktokProfile: createScavioTiktokProfileTool(config),
    scavioTiktokUserPosts: createScavioTiktokUserPostsTool(config),
    scavioTiktokVideo: createScavioTiktokVideoTool(config),
    scavioTiktokVideoComments: createScavioTiktokVideoCommentsTool(config),
    scavioTiktokCommentReplies: createScavioTiktokCommentRepliesTool(config),
    scavioTiktokSearchVideos: createScavioTiktokSearchVideosTool(config),
    scavioTiktokSearchUsers: createScavioTiktokSearchUsersTool(config),
    scavioTiktokHashtag: createScavioTiktokHashtagTool(config),
    scavioTiktokHashtagVideos: createScavioTiktokHashtagVideosTool(config),
    scavioTiktokUserFollowers: createScavioTiktokUserFollowersTool(config),
    scavioTiktokUserFollowings: createScavioTiktokUserFollowingsTool(config),
    scavioTiktokShopSearch: createScavioTiktokShopSearchTool(config),
    scavioTiktokShopSearchSuggestions: createScavioTiktokShopSearchSuggestionsTool(config),
    scavioTiktokShopProduct: createScavioTiktokShopProductTool(config),
    scavioTiktokShopProductReviews: createScavioTiktokShopProductReviewsTool(config),
    scavioTiktokShopCategories: createScavioTiktokShopCategoriesTool(config),
    scavioTiktokShopCategoryProducts: createScavioTiktokShopCategoryProductsTool(config),
    scavioTiktokShopShopProducts: createScavioTiktokShopShopProductsTool(config),
    scavioTiktokShopResolve: createScavioTiktokShopResolveTool(config),
    scavioInstagramProfile: createScavioInstagramProfileTool(config),
    scavioInstagramUserPosts: createScavioInstagramUserPostsTool(config),
    scavioInstagramUserReels: createScavioInstagramUserReelsTool(config),
    scavioInstagramUserTagged: createScavioInstagramUserTaggedTool(config),
    scavioInstagramUserStories: createScavioInstagramUserStoriesTool(config),
    scavioInstagramPost: createScavioInstagramPostTool(config),
    scavioInstagramPostComments: createScavioInstagramPostCommentsTool(config),
    scavioInstagramCommentReplies: createScavioInstagramCommentRepliesTool(config),
    scavioInstagramSearchUsers: createScavioInstagramSearchUsersTool(config),
    scavioInstagramSearchHashtags: createScavioInstagramSearchHashtagsTool(config),
    scavioInstagramUserFollowers: createScavioInstagramUserFollowersTool(config),
    scavioInstagramUserFollowings: createScavioInstagramUserFollowingsTool(config),
    scavioXSearch: createScavioXSearchTool(config),
    scavioXTweet: createScavioXTweetTool(config),
    scavioXTweetComments: createScavioXTweetCommentsTool(config),
    scavioXTweetRetweeters: createScavioXTweetRetweetersTool(config),
    scavioXUser: createScavioXUserTool(config),
    scavioXUserTweets: createScavioXUserTweetsTool(config),
    scavioXUserReplies: createScavioXUserRepliesTool(config),
    scavioXUserMedia: createScavioXUserMediaTool(config),
    scavioXUserFollowers: createScavioXUserFollowersTool(config),
    scavioXUserFollowings: createScavioXUserFollowingsTool(config),
    scavioXTrending: createScavioXTrendingTool(config),
    scavioLinkedinPerson: createScavioLinkedinPersonTool(config),
    scavioLinkedinPersonAbout: createScavioLinkedinPersonAboutTool(config),
    scavioLinkedinPersonPosts: createScavioLinkedinPersonPostsTool(config),
    scavioLinkedinCompany: createScavioLinkedinCompanyTool(config),
    scavioLinkedinCompanyPosts: createScavioLinkedinCompanyPostsTool(config),
    scavioLinkedinSearchJobs: createScavioLinkedinSearchJobsTool(config),
    scavioLinkedinJob: createScavioLinkedinJobTool(config),
    scavioLinkedinPost: createScavioLinkedinPostTool(config),
    scavioLinkedinPostComments: createScavioLinkedinPostCommentsTool(config),
    scavioThreadsProfile: createScavioThreadsProfileTool(config),
    scavioThreadsUserPosts: createScavioThreadsUserPostsTool(config),
    scavioThreadsUserReplies: createScavioThreadsUserRepliesTool(config),
    scavioThreadsPost: createScavioThreadsPostTool(config),
    scavioThreadsPostComments: createScavioThreadsPostCommentsTool(config),
    scavioThreadsSearchUsers: createScavioThreadsSearchUsersTool(config),
    scavioKuaishouProfile: createScavioKuaishouProfileTool(config),
    scavioKuaishouUserPosts: createScavioKuaishouUserPostsTool(config),
    scavioKuaishouUserLive: createScavioKuaishouUserLiveTool(config),
    scavioKuaishouUserResolve: createScavioKuaishouUserResolveTool(config),
    scavioKuaishouVideo: createScavioKuaishouVideoTool(config),
    scavioKuaishouVideoComments: createScavioKuaishouVideoCommentsTool(config),
    scavioKuaishouCommentReplies: createScavioKuaishouCommentRepliesTool(config),
    scavioKuaishouVideosBatch: createScavioKuaishouVideosBatchTool(config),
    scavioKuaishouSearch: createScavioKuaishouSearchTool(config),
    scavioKuaishouSearchVideos: createScavioKuaishouSearchVideosTool(config),
    scavioKuaishouSearchUsers: createScavioKuaishouSearchUsersTool(config),
    scavioKuaishouSearchLive: createScavioKuaishouSearchLiveTool(config),
    scavioKuaishouTagFeed: createScavioKuaishouTagFeedTool(config),
    scavioKuaishouTrending: createScavioKuaishouTrendingTool(config),
    scavioEbaySearch: createScavioEbaySearchTool(config),
    scavioEbayProduct: createScavioEbayProductTool(config),
    scavioEbaySeller: createScavioEbaySellerTool(config),
    scavioTargetSearch: createScavioTargetSearchTool(config),
    scavioTargetCategory: createScavioTargetCategoryTool(config),
    scavioTargetProduct: createScavioTargetProductTool(config),
    scavioTargetReviews: createScavioTargetReviewsTool(config),
    scavioHomeDepotSearch: createScavioHomeDepotSearchTool(config),
    scavioHomeDepotProduct: createScavioHomeDepotProductTool(config),
    scavioHomeDepotReviews: createScavioHomeDepotReviewsTool(config),
    scavioZillowSearch: createScavioZillowSearchTool(config),
    scavioZillowProperty: createScavioZillowPropertyTool(config),
    scavioZillowAgentReviews: createScavioZillowAgentReviewsTool(config),
    scavioBookingSearch: createScavioBookingSearchTool(config),
    scavioBookingHotel: createScavioBookingHotelTool(config),
    scavioBookingReviews: createScavioBookingReviewsTool(config),
    scavioTripadvisorLocations: createScavioTripadvisorLocationsTool(config),
    scavioTripadvisorSearch: createScavioTripadvisorSearchTool(config),
    scavioTripadvisorLocation: createScavioTripadvisorLocationTool(config),
    scavioTripadvisorReviews: createScavioTripadvisorReviewsTool(config),
    scavioIndeedSearch: createScavioIndeedSearchTool(config),
    scavioIndeedJob: createScavioIndeedJobTool(config),
    scavioIndeedCompany: createScavioIndeedCompanyTool(config),
    scavioIndeedCompanyReviews: createScavioIndeedCompanyReviewsTool(config),
    scavioAirbnbSearch: createScavioAirbnbSearchTool(config),
    scavioAirbnbListing: createScavioAirbnbListingTool(config),
    scavioAirbnbReviews: createScavioAirbnbReviewsTool(config),
    scavioGlassdoorCompanies: createScavioGlassdoorCompaniesTool(config),
    scavioGlassdoorCompany: createScavioGlassdoorCompanyTool(config),
    scavioGlassdoorReviews: createScavioGlassdoorReviewsTool(config),
    scavioGlassdoorSalaries: createScavioGlassdoorSalariesTool(config),
    scavioYelpSearch: createScavioYelpSearchTool(config),
    scavioYelpBusiness: createScavioYelpBusinessTool(config),
    scavioYelpReviews: createScavioYelpReviewsTool(config),
    scavioAppStoreSearch: createScavioAppStoreSearchTool(config),
    scavioAppStoreApp: createScavioAppStoreAppTool(config),
    scavioAppStoreReviews: createScavioAppStoreReviewsTool(config),
    scavioGooglePlaySearch: createScavioGooglePlaySearchTool(config),
    scavioGooglePlayApp: createScavioGooglePlayAppTool(config),
    scavioGooglePlayReviews: createScavioGooglePlayReviewsTool(config),
    scavioSecLookup: createScavioSecLookupTool(config),
    scavioSecCompany: createScavioSecCompanyTool(config),
    scavioSecFilings: createScavioSecFilingsTool(config),
    scavioSecConcept: createScavioSecConceptTool(config),
    scavioSecFacts: createScavioSecFactsTool(config),
    scavioSecSearch: createScavioSecSearchTool(config),
    scavioRedfinSearch: createScavioRedfinSearchTool(config),
    scavioRedfinProperty: createScavioRedfinPropertyTool(config),
    scavioRedfinMarket: createScavioRedfinMarketTool(config),
    scavioCompaniesHouseSearch: createScavioCompaniesHouseSearchTool(config),
    scavioCompaniesHouseCompany: createScavioCompaniesHouseCompanyTool(config),
    scavioCompaniesHouseOfficers: createScavioCompaniesHouseOfficersTool(config),
    scavioCompaniesHouseFilingHistory: createScavioCompaniesHouseFilingHistoryTool(config),
    scavioG2Search: createScavioG2SearchTool(config),
    scavioG2Product: createScavioG2ProductTool(config),
    scavioG2Reviews: createScavioG2ReviewsTool(config),
    scavioCapterraSearch: createScavioCapterraSearchTool(config),
    scavioCapterraProduct: createScavioCapterraProductTool(config),
    scavioCapterraReviews: createScavioCapterraReviewsTool(config),
    scavioGoogleAdsAdvertisers: createScavioGoogleAdsAdvertisersTool(config),
    scavioGoogleAdsSearch: createScavioGoogleAdsSearchTool(config),
    scavioGoogleAdsCreative: createScavioGoogleAdsCreativeTool(config),
    scavioMetaAdsSearch: createScavioMetaAdsSearchTool(config),
    scavioMetaAdsAdvertiser: createScavioMetaAdsAdvertiserTool(config),
    scavioMetaAdsAd: createScavioMetaAdsAdTool(config),
  };
}
