import type { ScavioClientOptions } from './client.js';
import {
  createScavioAmazonOffersTool,
  createScavioAmazonProductTool,
  createScavioAmazonSearchTool,
} from './amazon.js';
import {
  createScavioGoogleAiModeTool,
  createScavioGoogleFlightsTool,
  createScavioGoogleHotelsDetailTool,
  createScavioGoogleHotelsTool,
  createScavioGoogleMapsPlaceTool,
  createScavioGoogleMapsReviewsTool,
  createScavioGoogleMapsSearchTool,
  createScavioGoogleNewsTool,
  createScavioGoogleSearchTool,
  createScavioGoogleShoppingProductTool,
  createScavioGoogleShoppingStoresTool,
  createScavioGoogleShoppingTool,
  createScavioGoogleTrendingTool,
  createScavioGoogleTrendsTool,
} from './google.js';
import {
  createScavioInstagramCommentRepliesTool,
  createScavioInstagramPostCommentsTool,
  createScavioInstagramPostTool,
  createScavioInstagramProfileTool,
  createScavioInstagramSearchHashtagsTool,
  createScavioInstagramSearchUsersTool,
  createScavioInstagramUserFollowersTool,
  createScavioInstagramUserFollowingsTool,
  createScavioInstagramUserPostsTool,
  createScavioInstagramUserReelsTool,
  createScavioInstagramUserStoriesTool,
  createScavioInstagramUserTaggedTool,
} from './instagram.js';
import {
  createScavioLinkedinCompanyPostsTool,
  createScavioLinkedinCompanyTool,
  createScavioLinkedinJobTool,
  createScavioLinkedinPersonAboutTool,
  createScavioLinkedinPersonPostsTool,
  createScavioLinkedinPersonTool,
  createScavioLinkedinPostCommentsTool,
  createScavioLinkedinPostTool,
  createScavioLinkedinSearchJobsTool,
} from './linkedin.js';
import {
  createScavioRedditCommentRepliesTool,
  createScavioRedditPopularTool,
  createScavioRedditPostCommentsTool,
  createScavioRedditPostTool,
  createScavioRedditSearchSuggestionsTool,
  createScavioRedditSearchTool,
  createScavioRedditSubredditPostsTool,
  createScavioRedditSubredditTool,
  createScavioRedditTrendingTool,
  createScavioRedditUserCommentsTool,
  createScavioRedditUserPostsTool,
  createScavioRedditUserTool,
} from './reddit.js';
import {
  createScavioTiktokShopCategoriesTool,
  createScavioTiktokShopCategoryProductsTool,
  createScavioTiktokShopProductReviewsTool,
  createScavioTiktokShopProductTool,
  createScavioTiktokShopResolveTool,
  createScavioTiktokShopSearchSuggestionsTool,
  createScavioTiktokShopSearchTool,
  createScavioTiktokShopShopProductsTool,
} from './tiktok-shop.js';
import {
  createScavioTiktokCommentRepliesTool,
  createScavioTiktokHashtagTool,
  createScavioTiktokHashtagVideosTool,
  createScavioTiktokProfileTool,
  createScavioTiktokSearchUsersTool,
  createScavioTiktokSearchVideosTool,
  createScavioTiktokUserFollowersTool,
  createScavioTiktokUserFollowingsTool,
  createScavioTiktokUserPostsTool,
  createScavioTiktokVideoCommentsTool,
  createScavioTiktokVideoTool,
} from './tiktok.js';
import { createScavioWalmartProductTool, createScavioWalmartSearchTool } from './walmart.js';
import {
  createScavioXSearchTool,
  createScavioXTrendingTool,
  createScavioXTweetCommentsTool,
  createScavioXTweetRetweetersTool,
  createScavioXTweetTool,
  createScavioXUserFollowersTool,
  createScavioXUserFollowingsTool,
  createScavioXUserMediaTool,
  createScavioXUserRepliesTool,
  createScavioXUserTool,
  createScavioXUserTweetsTool,
} from './x.js';
import {
  createScavioYoutubeChannelCommunityTool,
  createScavioYoutubeChannelResolveTool,
  createScavioYoutubeChannelSearchTool,
  createScavioYoutubeChannelShortsTool,
  createScavioYoutubeChannelTool,
  createScavioYoutubeChannelVideosTool,
  createScavioYoutubeCommentRepliesTool,
  createScavioYoutubeCommentsTool,
  createScavioYoutubeRelatedTool,
  createScavioYoutubeSearchTool,
  createScavioYoutubeShortsTool,
  createScavioYoutubeStreamsTool,
  createScavioYoutubeSuggestionsTool,
  createScavioYoutubeTranscriptTool,
  createScavioYoutubeVideoTool,
} from './youtube.js';

/**
 * Every Scavio tool, keyed by name. This list and the exact-order assertion in
 * src/__tests__/tools.test.ts are the package's two hardcoded registries - a new
 * tool must land in both, or it ships unreachable.
 */
export function createScavioTools(config?: ScavioClientOptions) {
  return {
    scavioGoogleSearch: createScavioGoogleSearchTool(config),
    scavioGoogleAiMode: createScavioGoogleAiModeTool(config),
    scavioGoogleMapsSearch: createScavioGoogleMapsSearchTool(config),
    scavioGoogleMapsPlace: createScavioGoogleMapsPlaceTool(config),
    scavioGoogleMapsReviews: createScavioGoogleMapsReviewsTool(config),
    scavioGoogleShopping: createScavioGoogleShoppingTool(config),
    scavioGoogleShoppingProduct: createScavioGoogleShoppingProductTool(config),
    scavioGoogleShoppingStores: createScavioGoogleShoppingStoresTool(config),
    scavioGoogleFlights: createScavioGoogleFlightsTool(config),
    scavioGoogleHotels: createScavioGoogleHotelsTool(config),
    scavioGoogleHotelsDetail: createScavioGoogleHotelsDetailTool(config),
    scavioGoogleNews: createScavioGoogleNewsTool(config),
    scavioGoogleTrends: createScavioGoogleTrendsTool(config),
    scavioGoogleTrending: createScavioGoogleTrendingTool(config),
    scavioAmazonSearch: createScavioAmazonSearchTool(config),
    scavioAmazonProduct: createScavioAmazonProductTool(config),
    scavioAmazonOffers: createScavioAmazonOffersTool(config),
    scavioWalmartSearch: createScavioWalmartSearchTool(config),
    scavioWalmartProduct: createScavioWalmartProductTool(config),
    scavioYoutubeSearch: createScavioYoutubeSearchTool(config),
    scavioYoutubeShorts: createScavioYoutubeShortsTool(config),
    scavioYoutubeSuggestions: createScavioYoutubeSuggestionsTool(config),
    scavioYoutubeVideo: createScavioYoutubeVideoTool(config),
    scavioYoutubeComments: createScavioYoutubeCommentsTool(config),
    scavioYoutubeCommentReplies: createScavioYoutubeCommentRepliesTool(config),
    scavioYoutubeTranscript: createScavioYoutubeTranscriptTool(config),
    scavioYoutubeRelated: createScavioYoutubeRelatedTool(config),
    scavioYoutubeChannelSearch: createScavioYoutubeChannelSearchTool(config),
    scavioYoutubeChannel: createScavioYoutubeChannelTool(config),
    scavioYoutubeChannelVideos: createScavioYoutubeChannelVideosTool(config),
    scavioYoutubeChannelShorts: createScavioYoutubeChannelShortsTool(config),
    scavioYoutubeChannelCommunity: createScavioYoutubeChannelCommunityTool(config),
    scavioYoutubeChannelResolve: createScavioYoutubeChannelResolveTool(config),
    scavioYoutubeStreams: createScavioYoutubeStreamsTool(config),
    scavioRedditSearch: createScavioRedditSearchTool(config),
    scavioRedditSearchSuggestions: createScavioRedditSearchSuggestionsTool(config),
    scavioRedditPost: createScavioRedditPostTool(config),
    scavioRedditPostComments: createScavioRedditPostCommentsTool(config),
    scavioRedditCommentReplies: createScavioRedditCommentRepliesTool(config),
    scavioRedditSubreddit: createScavioRedditSubredditTool(config),
    scavioRedditSubredditPosts: createScavioRedditSubredditPostsTool(config),
    scavioRedditUser: createScavioRedditUserTool(config),
    scavioRedditUserPosts: createScavioRedditUserPostsTool(config),
    scavioRedditUserComments: createScavioRedditUserCommentsTool(config),
    scavioRedditPopular: createScavioRedditPopularTool(config),
    scavioRedditTrending: createScavioRedditTrendingTool(config),
    scavioTiktokProfile: createScavioTiktokProfileTool(config),
    scavioTiktokUserPosts: createScavioTiktokUserPostsTool(config),
    scavioTiktokVideo: createScavioTiktokVideoTool(config),
    scavioTiktokVideoComments: createScavioTiktokVideoCommentsTool(config),
    scavioTiktokCommentReplies: createScavioTiktokCommentRepliesTool(config),
    scavioTiktokSearchVideos: createScavioTiktokSearchVideosTool(config),
    scavioTiktokSearchUsers: createScavioTiktokSearchUsersTool(config),
    scavioTiktokHashtag: createScavioTiktokHashtagTool(config),
    scavioTiktokHashtagVideos: createScavioTiktokHashtagVideosTool(config),
    scavioTiktokUserFollowers: createScavioTiktokUserFollowersTool(config),
    scavioTiktokUserFollowings: createScavioTiktokUserFollowingsTool(config),
    scavioTiktokShopSearch: createScavioTiktokShopSearchTool(config),
    scavioTiktokShopSearchSuggestions: createScavioTiktokShopSearchSuggestionsTool(config),
    scavioTiktokShopProduct: createScavioTiktokShopProductTool(config),
    scavioTiktokShopProductReviews: createScavioTiktokShopProductReviewsTool(config),
    scavioTiktokShopCategories: createScavioTiktokShopCategoriesTool(config),
    scavioTiktokShopCategoryProducts: createScavioTiktokShopCategoryProductsTool(config),
    scavioTiktokShopShopProducts: createScavioTiktokShopShopProductsTool(config),
    scavioTiktokShopResolve: createScavioTiktokShopResolveTool(config),
    scavioInstagramProfile: createScavioInstagramProfileTool(config),
    scavioInstagramUserPosts: createScavioInstagramUserPostsTool(config),
    scavioInstagramUserReels: createScavioInstagramUserReelsTool(config),
    scavioInstagramUserTagged: createScavioInstagramUserTaggedTool(config),
    scavioInstagramUserStories: createScavioInstagramUserStoriesTool(config),
    scavioInstagramPost: createScavioInstagramPostTool(config),
    scavioInstagramPostComments: createScavioInstagramPostCommentsTool(config),
    scavioInstagramCommentReplies: createScavioInstagramCommentRepliesTool(config),
    scavioInstagramSearchUsers: createScavioInstagramSearchUsersTool(config),
    scavioInstagramSearchHashtags: createScavioInstagramSearchHashtagsTool(config),
    scavioInstagramUserFollowers: createScavioInstagramUserFollowersTool(config),
    scavioInstagramUserFollowings: createScavioInstagramUserFollowingsTool(config),
    scavioXSearch: createScavioXSearchTool(config),
    scavioXTweet: createScavioXTweetTool(config),
    scavioXTweetComments: createScavioXTweetCommentsTool(config),
    scavioXTweetRetweeters: createScavioXTweetRetweetersTool(config),
    scavioXUser: createScavioXUserTool(config),
    scavioXUserTweets: createScavioXUserTweetsTool(config),
    scavioXUserReplies: createScavioXUserRepliesTool(config),
    scavioXUserMedia: createScavioXUserMediaTool(config),
    scavioXUserFollowers: createScavioXUserFollowersTool(config),
    scavioXUserFollowings: createScavioXUserFollowingsTool(config),
    scavioXTrending: createScavioXTrendingTool(config),
    scavioLinkedinPerson: createScavioLinkedinPersonTool(config),
    scavioLinkedinPersonAbout: createScavioLinkedinPersonAboutTool(config),
    scavioLinkedinPersonPosts: createScavioLinkedinPersonPostsTool(config),
    scavioLinkedinCompany: createScavioLinkedinCompanyTool(config),
    scavioLinkedinCompanyPosts: createScavioLinkedinCompanyPostsTool(config),
    scavioLinkedinSearchJobs: createScavioLinkedinSearchJobsTool(config),
    scavioLinkedinJob: createScavioLinkedinJobTool(config),
    scavioLinkedinPost: createScavioLinkedinPostTool(config),
    scavioLinkedinPostComments: createScavioLinkedinPostCommentsTool(config),
  };
}
